# Generated by Django 3.2.14 on 2022-07-07 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedtitle', models.CharField(default='Missing', max_length=500)),
                ('feedeventteam1', models.CharField(default='', max_length=300)),
                ('feedeventteam2', models.CharField(default='', max_length=300)),
                ('feedstart', models.DateTimeField(auto_now=True)),
                ('feedend', models.DateTimeField(blank=True, default='0001-01-01 00:00:01', null=True)),
                ('eventtype', models.CharField(blank=True, default='', max_length=250)),
                ('eventresult', models.CharField(default=None, max_length=500, null=True)),
                ('feedstatus', models.CharField(default='live', max_length=100)),
                ('feedpath', models.CharField(default='', max_length=500)),
                ('deleted', models.BooleanField(default=False)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('updateuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feeds Table',
                'db_table': 'feedman_feeds',
            },
        ),
    ]
